HELP!!!
12-23 21:36:37.096 5328-5328/com.github.guwenk.smuradio E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.github.guwenk.smuradio, PID: 5328
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.guwenk.smuradio/com.github.guwenk.smuradio.VoteActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2572)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654)
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                              at android.os.Looper.loop(Looper.java:207)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                              at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
                                                                           Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
                                                                              at com.github.guwenk.smuradio.VoteActivity.onCreate(VoteActivity.java:33)
                                                                              at android.app.Activity.performCreate(Activity.java:6309)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654) 
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                              at android.os.Looper.loop(Looper.java:207) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5728) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                              at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134) 